# sycl runtime components depends on 2.28 glibc.
c_stdlib_sycl_version:  # [linux]
  - 2.28                # [linux]
c_stdlib_version:       # [linux]
  - 2.17                # [linux]
mkl:
  - 2025
# Use image with support of glibc 2.28
docker_image:
- quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux and x86_64]
