azure:
  free_disk_space: true
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      SET_PAGEFILE: "True"
      MINIFORGE_HOME: C:\Miniforge
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
